media_folder: src/assets/images
public_folder: /media

connect-src: "https://api.cloudflare.com"

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'

backend:
  name: github
  repo: "coolxer/shinning-solstice"
  branch: main
  skip_ci: true
  base_url: "https://sveltia-cms-auth.lukasz-milos-dev.workers.dev/"

collections:
  - name: posts
    label: Posty
    label_singular: Post
    folder: src/posts
    create: true
    media_folder: /assets/images/posts
    public_folder: /media/posts
    fields:
      - name: title
        label: Tytul
      - name: description
        label: Opis
        widget: text
        required: false
      - name: date
        label: Data
        widget: datetime
        time_format: false
        required: false
